# Cloud Build設定（自動デプロイ用）
steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sizuka-app', '-f', 'Dockerfile.cloudrun', '.']
  
  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sizuka-app']
  
  # Cloud Runにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sizuka-app'
      - '--image=gcr.io/$PROJECT_ID/sizuka-app'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--timeout=300'
      - '--max-instances=10'
      - '--set-env-vars=^||^SUPABASE_URL=${_SUPABASE_URL}||SUPABASE_KEY=${_SUPABASE_KEY}||RAKUTEN_SERVICE_SECRET=${_RAKUTEN_SERVICE_SECRET}||RAKUTEN_LICENSE_KEY=${_RAKUTEN_LICENSE_KEY}||PRODUCT_MASTER_SPREADSHEET_ID=${_PRODUCT_MASTER_SPREADSHEET_ID}'

substitutions:
  _SUPABASE_URL: ''
  _SUPABASE_KEY: ''
  _RAKUTEN_SERVICE_SECRET: ''
  _RAKUTEN_LICENSE_KEY: ''
  _PRODUCT_MASTER_SPREADSHEET_ID: ''