name: Amazon Daily Sync

on:
  schedule:
    # 毎日日本時間9時に実行
    - cron: '0 0 * * *'  # UTC 0:00 = JST 9:00
  workflow_dispatch:  # 手動実行も可能

jobs:
  amazon-daily-sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Amazon Daily Sync
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        AMAZON_KEY: ${{ secrets.AMAZON_KEY }}
        AMAZON_SECRET: ${{ secrets.AMAZON_SECRET }}
      run: python amazon_sp_api_sync.py daily