name: Daily Sync and Keep Alive

on:
  schedule:
    # 毎日日本時間9時に実行
    - cron: '0 0 * * *'  # UTC 0:00 = JST 9:00
  workflow_dispatch:  # 手動実行も可能

jobs:
  sync-orders:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Keep Supabase Alive
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python keep_alive.py
    
    - name: Sync Rakuten Orders
      if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        RAKUTEN_SERVICE_SECRET: ${{ secrets.RAKUTEN_SERVICE_SECRET }}
        RAKUTEN_LICENSE_KEY: ${{ secrets.RAKUTEN_LICENSE_KEY }}
      run: python daily_sync.py
    
    - name: Sync Amazon Orders
      if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        AMAZON_CLIENT_ID: ${{ secrets.AMAZON_CLIENT_ID }}
        AMAZON_CLIENT_SECRET: ${{ secrets.AMAZON_CLIENT_SECRET }}
        AMAZON_REFRESH_TOKEN: ${{ secrets.AMAZON_REFRESH_TOKEN }}
        AMAZON_MARKETPLACE_ID: ${{ secrets.AMAZON_MARKETPLACE_ID }}
        AMAZON_REGION: ${{ secrets.AMAZON_REGION }}
      run: python correct_amazon_sync.py daily
    
    - name: Sync Manufacturing Inventory
      if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python daily_manufacturing_sync.py --auto
    
