name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: sizuka-inventory-system
  SERVICE_NAME: sizuka-inventory-system
  REGION: asia-northeast1
  IMAGE_NAME: sizuka-inventory

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker to use gcloud as credential helper
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -f Dockerfile.cloudrun -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .

    - name: Push Docker image to Container Registry
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --timeout 300

    - name: Get service URL
      run: |
        URL=$(gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)')
        echo "Service deployed at: $URL"
        echo "SERVICE_URL=$URL" >> $GITHUB_ENV

    - name: Test deployment
      run: |
        curl -f $SERVICE_URL/health || exit 1
        echo "Deployment test passed!"